name: Docker Push

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "20 20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test docker login
        run: echo "DOCKER_USERNAME -> ${DOCKER_USERNAME}; DOCKER_PASSWORD -> ${DOCKER_PASSWORD};"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: . env/docker.build.sh

      - name: Push image
        run: . env/docker.push.sh # $(date +%s)
